name: Meson build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  packagename: assref-git-${{ github.sha }}
  prefix: ${{ github.workspace }}/builddir/assref-git-${{ github.sha }}

jobs:
  build:
    strategy:
      matrix:
        buildtype: ["debug", "release"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Meson and dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get install \
          meson \
          liblua5.3-dev \
          libgtest-dev

    - name: Configure project
      run: |
        meson setup \
          --backend ninja \
          --buildtype ${{ matrix.buildtype }} \
          --prefix=${{ env.prefix }} \
          -Dlua=lua5.3 \
          builddir

    - name: Build
      run: |
        ninja -C builddir
        ninja -C builddir test
        ninja -C builddir install

    - name: Package
      if: github.event_name == 'push'
      working-directory: ./builddir
      run: |
        tar -cJf ${{ env.packagename }}.tar.xz ${{ env.packagename }}

    - name: Upload artifacts
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: assref
        path: builddir/${{ env.packagename }}.tar.xz

